/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTranslationsRouteImport } from './routes/admin.translations'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMakeupRouteImport } from './routes/admin.makeup'
import { Route as AdminLessonsRouteImport } from './routes/admin.lessons'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminExportRouteImport } from './routes/admin.export'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminCitiesRouteImport } from './routes/admin.cities'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => LessonsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTranslationsRoute = AdminTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMakeupRoute = AdminMakeupRouteImport.update({
  id: '/makeup',
  path: '/makeup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCitiesRoute = AdminCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/language': typeof LanguageRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/makeup': typeof AdminMakeupRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/language': typeof LanguageRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/makeup': typeof AdminMakeupRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/language': typeof LanguageRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/makeup': typeof AdminMakeupRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai'
    | '/community'
    | '/dashboard'
    | '/language'
    | '/lessons'
    | '/login'
    | '/profile'
    | '/quiz'
    | '/teacher'
    | '/admin/attendance'
    | '/admin/branches'
    | '/admin/candidates'
    | '/admin/cities'
    | '/admin/classes'
    | '/admin/export'
    | '/admin/import'
    | '/admin/lessons'
    | '/admin/makeup'
    | '/admin/notifications'
    | '/admin/staff'
    | '/admin/translations'
    | '/admin/users'
    | '/lessons/$lessonId'
    | '/teacher/attendance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai'
    | '/community'
    | '/dashboard'
    | '/language'
    | '/lessons'
    | '/login'
    | '/profile'
    | '/quiz'
    | '/teacher'
    | '/admin/attendance'
    | '/admin/branches'
    | '/admin/candidates'
    | '/admin/cities'
    | '/admin/classes'
    | '/admin/export'
    | '/admin/import'
    | '/admin/lessons'
    | '/admin/makeup'
    | '/admin/notifications'
    | '/admin/staff'
    | '/admin/translations'
    | '/admin/users'
    | '/lessons/$lessonId'
    | '/teacher/attendance'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai'
    | '/community'
    | '/dashboard'
    | '/language'
    | '/lessons'
    | '/login'
    | '/profile'
    | '/quiz'
    | '/teacher'
    | '/admin/attendance'
    | '/admin/branches'
    | '/admin/candidates'
    | '/admin/cities'
    | '/admin/classes'
    | '/admin/export'
    | '/admin/import'
    | '/admin/lessons'
    | '/admin/makeup'
    | '/admin/notifications'
    | '/admin/staff'
    | '/admin/translations'
    | '/admin/users'
    | '/lessons/$lessonId'
    | '/teacher/attendance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiRoute: typeof AiRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  LanguageRoute: typeof LanguageRoute
  LessonsRoute: typeof LessonsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/translations': {
      id: '/admin/translations'
      path: '/translations'
      fullPath: '/admin/translations'
      preLoaderRoute: typeof AdminTranslationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/makeup': {
      id: '/admin/makeup'
      path: '/makeup'
      fullPath: '/admin/makeup'
      preLoaderRoute: typeof AdminMakeupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cities': {
      id: '/admin/cities'
      path: '/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AdminCitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminCitiesRoute: typeof AdminCitiesRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminMakeupRoute: typeof AdminMakeupRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTranslationsRoute: typeof AdminTranslationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminBranchesRoute: AdminBranchesRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminCitiesRoute: AdminCitiesRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminExportRoute: AdminExportRoute,
  AdminImportRoute: AdminImportRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminMakeupRoute: AdminMakeupRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTranslationsRoute: AdminTranslationsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LessonsRouteChildren {
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
}

const LessonsRouteChildren: LessonsRouteChildren = {
  LessonsLessonIdRoute: LessonsLessonIdRoute,
}

const LessonsRouteWithChildren =
  LessonsRoute._addFileChildren(LessonsRouteChildren)

interface TeacherRouteChildren {
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAttendanceRoute: TeacherAttendanceRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiRoute: AiRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  LanguageRoute: LanguageRoute,
  LessonsRoute: LessonsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
