/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PsychDiagnosticRouteImport } from './routes/psych-diagnostic'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BeqaHistoryRouteImport } from './routes/beqa-history'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'
import { Route as ClassroomSessionIdRouteImport } from './routes/classroom.$sessionId'
import { Route as AdminVouchersRouteImport } from './routes/admin.vouchers'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTranslationsRouteImport } from './routes/admin.translations'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminProgressRouteImport } from './routes/admin.progress'
import { Route as AdminOrganizationRouteImport } from './routes/admin.organization'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMaterialsRouteImport } from './routes/admin.materials'
import { Route as AdminMakeupRouteImport } from './routes/admin.makeup'
import { Route as AdminLessonsRouteImport } from './routes/admin.lessons'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminExportRouteImport } from './routes/admin.export'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminDiagnosticsRouteImport } from './routes/admin.diagnostics'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminCitiesRouteImport } from './routes/admin.cities'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'
import { Route as AdminBeqaRouteImport } from './routes/admin.beqa'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAiAgentRouteImport } from './routes/admin.ai-agent'
import { Route as AdminExamsExamIdRouteImport } from './routes/admin.exams.$examId'
import { Route as AdminAttendanceDrilldownRouteImport } from './routes/admin.attendance.drilldown'
import { Route as ApiPublicHooksNotificationsTickRouteImport } from './routes/api/public/hooks/notifications-tick'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PsychDiagnosticRoute = PsychDiagnosticRouteImport.update({
  id: '/psych-diagnostic',
  path: '/psych-diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BeqaHistoryRoute = BeqaHistoryRouteImport.update({
  id: '/beqa-history',
  path: '/beqa-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => LessonsRoute,
} as any)
const ClassroomSessionIdRoute = ClassroomSessionIdRouteImport.update({
  id: '/classroom/$sessionId',
  path: '/classroom/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVouchersRoute = AdminVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTranslationsRoute = AdminTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgressRoute = AdminProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationRoute = AdminOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaterialsRoute = AdminMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMakeupRoute = AdminMakeupRouteImport.update({
  id: '/makeup',
  path: '/makeup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnosticsRoute = AdminDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCitiesRoute = AdminCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBeqaRoute = AdminBeqaRouteImport.update({
  id: '/beqa',
  path: '/beqa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiAgentRoute = AdminAiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsExamIdRoute = AdminExamsExamIdRouteImport.update({
  id: '/$examId',
  path: '/$examId',
  getParentRoute: () => AdminExamsRoute,
} as any)
const AdminAttendanceDrilldownRoute =
  AdminAttendanceDrilldownRouteImport.update({
    id: '/drilldown',
    path: '/drilldown',
    getParentRoute: () => AdminAttendanceRoute,
  } as any)
const ApiPublicHooksNotificationsTickRoute =
  ApiPublicHooksNotificationsTickRouteImport.update({
    id: '/api/public/hooks/notifications-tick',
    path: '/api/public/hooks/notifications-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/beqa-history': typeof BeqaHistoryRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/language': typeof LanguageRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/psych-diagnostic': typeof PsychDiagnosticRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/ai-agent': typeof AdminAiAgentRoute
  '/admin/attendance': typeof AdminAttendanceRouteWithChildren
  '/admin/beqa': typeof AdminBeqaRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/exams': typeof AdminExamsRouteWithChildren
  '/admin/export': typeof AdminExportRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/makeup': typeof AdminMakeupRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/progress': typeof AdminProgressRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/classroom/$sessionId': typeof ClassroomSessionIdRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/admin/attendance/drilldown': typeof AdminAttendanceDrilldownRoute
  '/admin/exams/$examId': typeof AdminExamsExamIdRoute
  '/api/public/hooks/notifications-tick': typeof ApiPublicHooksNotificationsTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/beqa-history': typeof BeqaHistoryRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/language': typeof LanguageRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/psych-diagnostic': typeof PsychDiagnosticRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/ai-agent': typeof AdminAiAgentRoute
  '/admin/attendance': typeof AdminAttendanceRouteWithChildren
  '/admin/beqa': typeof AdminBeqaRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/exams': typeof AdminExamsRouteWithChildren
  '/admin/export': typeof AdminExportRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/makeup': typeof AdminMakeupRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/progress': typeof AdminProgressRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/classroom/$sessionId': typeof ClassroomSessionIdRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/admin/attendance/drilldown': typeof AdminAttendanceDrilldownRoute
  '/admin/exams/$examId': typeof AdminExamsExamIdRoute
  '/api/public/hooks/notifications-tick': typeof ApiPublicHooksNotificationsTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/beqa-history': typeof BeqaHistoryRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/language': typeof LanguageRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/psych-diagnostic': typeof PsychDiagnosticRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/ai-agent': typeof AdminAiAgentRoute
  '/admin/attendance': typeof AdminAttendanceRouteWithChildren
  '/admin/beqa': typeof AdminBeqaRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/exams': typeof AdminExamsRouteWithChildren
  '/admin/export': typeof AdminExportRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/makeup': typeof AdminMakeupRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/progress': typeof AdminProgressRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/classroom/$sessionId': typeof ClassroomSessionIdRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/admin/attendance/drilldown': typeof AdminAttendanceDrilldownRoute
  '/admin/exams/$examId': typeof AdminExamsExamIdRoute
  '/api/public/hooks/notifications-tick': typeof ApiPublicHooksNotificationsTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai'
    | '/beqa-history'
    | '/community'
    | '/dashboard'
    | '/diagnostics'
    | '/language'
    | '/lessons'
    | '/login'
    | '/profile'
    | '/psych-diagnostic'
    | '/quiz'
    | '/reset-password'
    | '/schedule'
    | '/teacher'
    | '/admin/ai-agent'
    | '/admin/attendance'
    | '/admin/beqa'
    | '/admin/branches'
    | '/admin/candidates'
    | '/admin/cities'
    | '/admin/classes'
    | '/admin/content'
    | '/admin/diagnostics'
    | '/admin/exams'
    | '/admin/export'
    | '/admin/import'
    | '/admin/inbox'
    | '/admin/lessons'
    | '/admin/makeup'
    | '/admin/materials'
    | '/admin/notifications'
    | '/admin/organization'
    | '/admin/progress'
    | '/admin/schedule'
    | '/admin/staff'
    | '/admin/teachers'
    | '/admin/translations'
    | '/admin/users'
    | '/admin/vouchers'
    | '/classroom/$sessionId'
    | '/lessons/$lessonId'
    | '/teacher/attendance'
    | '/admin/attendance/drilldown'
    | '/admin/exams/$examId'
    | '/api/public/hooks/notifications-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai'
    | '/beqa-history'
    | '/community'
    | '/dashboard'
    | '/diagnostics'
    | '/language'
    | '/lessons'
    | '/login'
    | '/profile'
    | '/psych-diagnostic'
    | '/quiz'
    | '/reset-password'
    | '/schedule'
    | '/teacher'
    | '/admin/ai-agent'
    | '/admin/attendance'
    | '/admin/beqa'
    | '/admin/branches'
    | '/admin/candidates'
    | '/admin/cities'
    | '/admin/classes'
    | '/admin/content'
    | '/admin/diagnostics'
    | '/admin/exams'
    | '/admin/export'
    | '/admin/import'
    | '/admin/inbox'
    | '/admin/lessons'
    | '/admin/makeup'
    | '/admin/materials'
    | '/admin/notifications'
    | '/admin/organization'
    | '/admin/progress'
    | '/admin/schedule'
    | '/admin/staff'
    | '/admin/teachers'
    | '/admin/translations'
    | '/admin/users'
    | '/admin/vouchers'
    | '/classroom/$sessionId'
    | '/lessons/$lessonId'
    | '/teacher/attendance'
    | '/admin/attendance/drilldown'
    | '/admin/exams/$examId'
    | '/api/public/hooks/notifications-tick'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai'
    | '/beqa-history'
    | '/community'
    | '/dashboard'
    | '/diagnostics'
    | '/language'
    | '/lessons'
    | '/login'
    | '/profile'
    | '/psych-diagnostic'
    | '/quiz'
    | '/reset-password'
    | '/schedule'
    | '/teacher'
    | '/admin/ai-agent'
    | '/admin/attendance'
    | '/admin/beqa'
    | '/admin/branches'
    | '/admin/candidates'
    | '/admin/cities'
    | '/admin/classes'
    | '/admin/content'
    | '/admin/diagnostics'
    | '/admin/exams'
    | '/admin/export'
    | '/admin/import'
    | '/admin/inbox'
    | '/admin/lessons'
    | '/admin/makeup'
    | '/admin/materials'
    | '/admin/notifications'
    | '/admin/organization'
    | '/admin/progress'
    | '/admin/schedule'
    | '/admin/staff'
    | '/admin/teachers'
    | '/admin/translations'
    | '/admin/users'
    | '/admin/vouchers'
    | '/classroom/$sessionId'
    | '/lessons/$lessonId'
    | '/teacher/attendance'
    | '/admin/attendance/drilldown'
    | '/admin/exams/$examId'
    | '/api/public/hooks/notifications-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiRoute: typeof AiRoute
  BeqaHistoryRoute: typeof BeqaHistoryRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  LanguageRoute: typeof LanguageRoute
  LessonsRoute: typeof LessonsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  PsychDiagnosticRoute: typeof PsychDiagnosticRoute
  QuizRoute: typeof QuizRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScheduleRoute: typeof ScheduleRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  ClassroomSessionIdRoute: typeof ClassroomSessionIdRoute
  ApiPublicHooksNotificationsTickRoute: typeof ApiPublicHooksNotificationsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psych-diagnostic': {
      id: '/psych-diagnostic'
      path: '/psych-diagnostic'
      fullPath: '/psych-diagnostic'
      preLoaderRoute: typeof PsychDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beqa-history': {
      id: '/beqa-history'
      path: '/beqa-history'
      fullPath: '/beqa-history'
      preLoaderRoute: typeof BeqaHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/classroom/$sessionId': {
      id: '/classroom/$sessionId'
      path: '/classroom/$sessionId'
      fullPath: '/classroom/$sessionId'
      preLoaderRoute: typeof ClassroomSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vouchers': {
      id: '/admin/vouchers'
      path: '/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AdminVouchersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/translations': {
      id: '/admin/translations'
      path: '/translations'
      fullPath: '/admin/translations'
      preLoaderRoute: typeof AdminTranslationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/progress': {
      id: '/admin/progress'
      path: '/progress'
      fullPath: '/admin/progress'
      preLoaderRoute: typeof AdminProgressRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organization': {
      id: '/admin/organization'
      path: '/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AdminOrganizationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materials': {
      id: '/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AdminMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/makeup': {
      id: '/admin/makeup'
      path: '/makeup'
      fullPath: '/admin/makeup'
      preLoaderRoute: typeof AdminMakeupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diagnostics': {
      id: '/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AdminDiagnosticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cities': {
      id: '/admin/cities'
      path: '/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AdminCitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/beqa': {
      id: '/admin/beqa'
      path: '/beqa'
      fullPath: '/admin/beqa'
      preLoaderRoute: typeof AdminBeqaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-agent': {
      id: '/admin/ai-agent'
      path: '/ai-agent'
      fullPath: '/admin/ai-agent'
      preLoaderRoute: typeof AdminAiAgentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams/$examId': {
      id: '/admin/exams/$examId'
      path: '/$examId'
      fullPath: '/admin/exams/$examId'
      preLoaderRoute: typeof AdminExamsExamIdRouteImport
      parentRoute: typeof AdminExamsRoute
    }
    '/admin/attendance/drilldown': {
      id: '/admin/attendance/drilldown'
      path: '/drilldown'
      fullPath: '/admin/attendance/drilldown'
      preLoaderRoute: typeof AdminAttendanceDrilldownRouteImport
      parentRoute: typeof AdminAttendanceRoute
    }
    '/api/public/hooks/notifications-tick': {
      id: '/api/public/hooks/notifications-tick'
      path: '/api/public/hooks/notifications-tick'
      fullPath: '/api/public/hooks/notifications-tick'
      preLoaderRoute: typeof ApiPublicHooksNotificationsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminAttendanceRouteChildren {
  AdminAttendanceDrilldownRoute: typeof AdminAttendanceDrilldownRoute
}

const AdminAttendanceRouteChildren: AdminAttendanceRouteChildren = {
  AdminAttendanceDrilldownRoute: AdminAttendanceDrilldownRoute,
}

const AdminAttendanceRouteWithChildren = AdminAttendanceRoute._addFileChildren(
  AdminAttendanceRouteChildren,
)

interface AdminExamsRouteChildren {
  AdminExamsExamIdRoute: typeof AdminExamsExamIdRoute
}

const AdminExamsRouteChildren: AdminExamsRouteChildren = {
  AdminExamsExamIdRoute: AdminExamsExamIdRoute,
}

const AdminExamsRouteWithChildren = AdminExamsRoute._addFileChildren(
  AdminExamsRouteChildren,
)

interface AdminRouteChildren {
  AdminAiAgentRoute: typeof AdminAiAgentRoute
  AdminAttendanceRoute: typeof AdminAttendanceRouteWithChildren
  AdminBeqaRoute: typeof AdminBeqaRoute
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminCitiesRoute: typeof AdminCitiesRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDiagnosticsRoute: typeof AdminDiagnosticsRoute
  AdminExamsRoute: typeof AdminExamsRouteWithChildren
  AdminExportRoute: typeof AdminExportRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminMakeupRoute: typeof AdminMakeupRoute
  AdminMaterialsRoute: typeof AdminMaterialsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrganizationRoute: typeof AdminOrganizationRoute
  AdminProgressRoute: typeof AdminProgressRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminTranslationsRoute: typeof AdminTranslationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVouchersRoute: typeof AdminVouchersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiAgentRoute: AdminAiAgentRoute,
  AdminAttendanceRoute: AdminAttendanceRouteWithChildren,
  AdminBeqaRoute: AdminBeqaRoute,
  AdminBranchesRoute: AdminBranchesRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminCitiesRoute: AdminCitiesRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDiagnosticsRoute: AdminDiagnosticsRoute,
  AdminExamsRoute: AdminExamsRouteWithChildren,
  AdminExportRoute: AdminExportRoute,
  AdminImportRoute: AdminImportRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminMakeupRoute: AdminMakeupRoute,
  AdminMaterialsRoute: AdminMaterialsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrganizationRoute: AdminOrganizationRoute,
  AdminProgressRoute: AdminProgressRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminTranslationsRoute: AdminTranslationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVouchersRoute: AdminVouchersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LessonsRouteChildren {
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
}

const LessonsRouteChildren: LessonsRouteChildren = {
  LessonsLessonIdRoute: LessonsLessonIdRoute,
}

const LessonsRouteWithChildren =
  LessonsRoute._addFileChildren(LessonsRouteChildren)

interface TeacherRouteChildren {
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAttendanceRoute: TeacherAttendanceRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiRoute: AiRoute,
  BeqaHistoryRoute: BeqaHistoryRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  LanguageRoute: LanguageRoute,
  LessonsRoute: LessonsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  PsychDiagnosticRoute: PsychDiagnosticRoute,
  QuizRoute: QuizRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScheduleRoute: ScheduleRoute,
  TeacherRoute: TeacherRouteWithChildren,
  ClassroomSessionIdRoute: ClassroomSessionIdRoute,
  ApiPublicHooksNotificationsTickRoute: ApiPublicHooksNotificationsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
